name: snapfix
description: "SnapFix – Smart Complaint Management System with AI-powered issue reporting and location tracking."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.3.3
  path: ^1.9.0

  # File & media handling
  file_picker: ^8.1.2
  image_picker: ^1.1.2

  # Location & maps
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

  # UI and styling
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.3

  # Error & crash handling (recommended for Play Store)
  sentry_flutter: ^8.3.0

  # Environment handling (for API_BASE_URL, etc.)
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Asset folder (images, animations, JSON, etc.)
  assets:
    - assets/
